spring:
  application:
    name: smart-service-booking
  
 
  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: jdbc:postgresql://ep-late-dew-a1j0cwg1-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_XYI7V1TcelNt
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true

server:
  port: 8080