spring:
  application:
    name: smart-service-booking

  main:
    allow-bean-definition-overriding: true  # <-- added this

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-late-dew-a1j0cwg1-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD:npg_XYI7V1TcelNt}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.temp.use_jdbc_metadata_defaults: false 

server:
  port: 8080
